name: The River
favicon: null
layout_spectrum: 0.4104477
typography_spectrum: 0.3847948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ACC5E9'
    - '#0D0503'
    - '#FB7702'
    - '#911603'
    - '#E9B491'
  brandStrength: 0.04759022
  lightness: 0.09841418
  saturation: 0.3363896
  rhythmicContrast: 0.7112873
purpose: []
